---
- name: installing httpd
  hosts: all
  become: true
  tasks:
  - name: installing a httpd 
    yum:
     name: httpd     
     state: installed
  - name: service httpd start
    service: 
     name: httpd
     state: started 
          
