---
- name: install multiple packages
  hosts: all
  become: true
  tasks:
  - name: install multiple packages  
    yum:
     name: ['git','tree','make','wget','mysql','gcc','docker']      
     state: installed
