---
- name: installing httpd
  hosts: all
  become: true
  tasks:
  - name: installing a httpd 
    yum:
     name: httpd     
     state: installed
  - name: service httpd start
    service: 
     name: httpd
     state: started 
  - name: copy index.html
    copy:
     src: /home/ansadmin/index.html
     dest: /var/www/html
     mode: 0777   
